name: Deployment
on:
  push:
    branches:
      - master
      - production

env:
  CURRENT_BRANCH: ${{ github.ref_name =='production' && 'production' || 'master' }}
  GCR_HOST: us.gcr.io
  GOOGLE_PROJECT_ID: babbage-private
  GCR_IMAGE_NAME: coinflip

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.DOCKER_REGISTRY_PUSH_KEY }}
          registry: ${{ env.GCR_HOST }}
          project_id: ${{ env.GOOGLE_PROJECT_ID }}
          image_name: ${{ env.GCR_IMAGE_NAME }}
          image_tag: latest,${{ env.CURRENT_BRANCH }}-${{ github.sha }}
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_deploy_creds }}
      - uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.GCR_IMAGE_NAME }}-${{ env.CURRENT_BRANCH }}
          image: "${{ env.GCR_HOST }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.GCR_IMAGE_NAME }}:${{ env.CURRENT_BRANCH }}-${{ github.sha }}"